# permissions for end users to view integrationjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integrationjob-viewer-role
rules:
- apiGroups:
  - cicd.tmax.io
  resources:
  - integrationjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cicd.tmax.io
  resources:
  - integrationjobs/status
  verbs:
  - get
