# permissions for end users to view integrationconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integrationconfig-viewer-role
rules:
- apiGroups:
  - cicd.tmax.io
  resources:
  - integrationconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cicd.tmax.io
  resources:
  - integrationconfigs/status
  verbs:
  - get
