# permissions for end users to edit integrationconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integrationconfig-editor-role
rules:
- apiGroups:
  - cicd.tmax.io
  resources:
  - integrationconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicd.tmax.io
  resources:
  - integrationconfigs/status
  verbs:
  - get
